# Generated by Django 5.2.4 on 2025-08-06 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='package_name',
        ),
    ]
